### ISSUE TITLE
Add continuous replication

### ISSUE THREAD

**Issue by pekrau** [pekrau/CouchDB2#103]
The URL is like
http://localhost:5984/DB_NAME/_changes/?feed=continuous\&include_docs=true

Doc here: https://docs.couchdb.org/en/stable/api/database/changes.html

Did you allready write the code (i think in Database class) ?

JFB (jfbaillette@g-echo.fr)

**Comment by dfreilich** [comment]
We were looking into using this library, but we need the `changes` method, both for stubbing during tests and to ensure that every attempt is traced. Is there any plan to implement it?

**Comment by pekrau** [comment]
I have now attempted an implementation of `db.change()` The new version is on PyPi. Try it and see if it behaves. I have just done a very basic test that it responds at all. I am not at all sure what the non-default values of the `feed` argument do.

If there are problems, please submit a bug issue with adequate description. Better yet, supply a pull request if you figure out a solution. It's not clear I will have time to figure out soon what `_changes` actually does if this implementation doesn't work.

**Comment by dfreilich** [comment]
Thank you! For our purposes, we need `feed=continuous` to work appropriately (we keep open the call to couchdb for the entire lifespan of the service), which doesn't seem to work just yet, but I appreciate you doing the initial implementation!
