### ISSUE TITLE
Broken import

### ISSUE THREAD

**Issue by BrodaUa** [pekrau/CouchDB2#106]
Package import does not work in virtualenv:

![image](https://user-images.githubusercontent.com/9928101/111292014-097ebc00-8648-11eb-857a-b259cee5d9d8.png)

Reproducing:
`virtualenv -p python3 .venv && source .venv/bin/activate && pip install couchdb2`
`pip freeze`
`python -c "import couchdb2"`
`python -c "import CouchDB2"`

**Comment by pekrau** [comment]
Thanks for this. I have somehow screwed up the upload to PyPi. While I figure out how to fix it, using

```
from CouchDB2 import couchdb2
```

works.

**Comment by pekrau** [comment]
I have yanked 1.9.4 from PyPi. Version 1.9.3 works, although without the latest improvements.

**Comment by BrodaUa** [comment]
@pekrau great, thank you! 
Import of 1.9.3 version works fine! 
But as I understand, 1.9.4 still has a problem, should I change the ticket title to _Broken import for 1.9.4_ ?

**Comment by pekrau** [comment]
Finally, updated version and functioning `setup.py`.
