### ISSUE TITLE
Return ID & Rev after Document PUT

### ISSUE THREAD

**Issue by N-Vlahovic** [pekrau/CouchDB2#123]
Hi,

I am a long time `couchdb-python` user and am currently merging to `couchdb2`.

I was wondering if it is possible to return the doc id & rev when `put`-ing a single document (it is my understanding `Database.put` returns `None`).

The workaround would be doing something of the form
```
# ...
success, identifier, revision = db.update([doc])
```
While working, this workaround seems less satisfying than something like `... = db.put(doc)`.

Is there something I am missing or am being overly pedantic here? If not, do you think this feature would be worth considering?

Best regards,

**Comment by pekrau** [comment]
Both the `_id` and `_rev` are updated in the `doc` when doing `db.put(doc)`. So I do not think it is necessary to return those values also.

You could create a subclass of Database and redefine `put` to do that, something like this:
```
class Database2(Database):
    def put(self, doc):
        super().put(doc)
        return doc["_id"], doc["_rev"]
```
