### ISSUE TITLE
Partitioned Database Creation Doesn't Work 

### ISSUE THREAD

**Issue by N-Vlahovic** [pekrau/CouchDB2#124]
Hi,

<h3>Description</h3>

I came across an issue when creating a database: using the keyword param `partitioned: bool` has no effect - the database is never partitioned even if `partitioned=True`.

<h3>Example</h3>

Here is a simple example:
```
import couchdb2

username: str = input("username: ")  # set username
password: str = input("password: ")  # set password

server = couchdb2.Server(
    href="http://localhost:5984",
    username=username,
    password=password,
)
print(server.up())
# True
db = server.get("test", check=False)
# Make sure db does not exist
try:
    db.destroy()
except couchdb2.NotFoundError:
    pass
# Create db
db.create(partitioned=True)
# Check props
print(db.get_info().get("props"))  # should contain "partitioned": true
# {}
```

<h3>Root Cause</h3>

Having a closer look at the requests sent we can observe `db.create` yields the following request
```
PUT
url: /test
body: n=3&q=8&partitioned=True    (as string)
```
whereas  `db.put({"_id": "hello", "name": "world"})` yields
```
PUT
url: /test/hello
body: {"_id": "hello", "name": "world"}    (as bytes)
```

It seems the body of the request sent (c.f. line 251 `response = self._session.put(self._href(segments), **kw)` in `couchdb2.py`) is at cause here. I believe either passing the body as json (i.e. `b"{"partioned": true", ...}"`) or as url params (i.e. `/test?partitioned=true&...`) should solve it. (I know for a fact that the second option works).

Finally, I actually wouldn't mind having a look at it myself and contributing to the project. Please do let me know if this would welcomed.

Best regards,
Niko

------

<h3>Edit 1</h3>

Here is a working example for the creation of a partitioned db using the API
```
import base64
import requests

try:
    db.destroy()
except couchdb2.NotFoundError:
    pass
response = requests.put(
    url="http://localhost:5984/test?partitioned=true",
    headers={
        "Authorization": "Basic %s" % base64.b64encode(f"{username}:{password}".encode()).decode()
    }
)
print(response.json())
# {'ok': True}
response = requests.get(
    url="http://localhost:5984/test",
    headers={
        "Authorization": "Basic %s" % base64.b64encode(f"{username}:{password}".encode()).decode()
    }
)
print(response.json().get("props"))
# {'partitioned': True}
```

------

<h3>Edit 2</h3>

Modifying the method `Database.create` as follows solves the issue
```
    def create(self, n=3, q=8, partitioned=False):
        """Creates the database. Raises 'CreationError' if it already exists.

        - `n`: The number of replicas.
        - `q`: The number of shards.
        - `partitioned`: Whether to create a partitioned database.
        """
        partitioned = str(partitioned).lower()
        self.server._PUT(f"{self.name}?{n=!s}&{q=!s}&{partitioned=!s}")
        return self
```

I tried to push a new branch but was not given permission to do so.

**Comment by pekrau** [comment]
Sorry for delay in responding. Fixing this in upcoming release.
