### ISSUE TITLE
transient vs persistent replications

### ISSUE THREAD

**Issue by elChapoSing** [pekrau/CouchDB2#83]
In the set_replicate function, should there be an option to choose the replication endpoint ?
'_replication' is the recommended way to setup replications now isn't it ?

from the docs :

> There are two different ways to set up a replication. The first one that was introduced into CouchDB leads do a replication that could be called transient. Transient means that there are no documents backing up the replication. So after a restart of the CouchDB server the replication will disapear. Later, the _replicator database was introduced, which keeps documents containing your replication parameters. Such a replication can be called persistent. <b>Transient replications were kept for backward compatibility</b>. Both replications can have different replication states.

   ```
 def set_replicate(self, doc):
        "Request, configure, or stop, a replication operation."
        return self._POST('_replicate', json=doc)
```

**Comment by pekrau** [comment]
Thanks for the PR. I didn't do anything since my need for this module suddenly went away (external reasons), but now I need it again.

**Comment by elChapoSing** [comment]
I ended up changing some stuff in the update function though. The return
does not make sense. Will push that tomorrow.

**Comment by elChapoSing** [comment]
my bad it was in there in fact. all good. thks for merging.
