### ISSUE TITLE
json.loads() error

### ISSUE THREAD

**Issue by vdanen** [pekrau/CouchDB2#93]
I just installed Couchdb2 via pip3 (1.8.2) and when I try to use the commandline tool (couchdb2) or try to read anything via my own code I always get:

```
Traceback (most recent call last):
  File "./inkdrop.py", line 7, in <module>
    for db in server:
  File "/usr/local/lib/python3.7/site-packages/couchdb2.py", line 81, in __iter__
    data = self._GET('_all_dbs').json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 888, in json
    return complexjson.loads(
AttributeError: module 'json' has no attribute 'loads'
```

With the cli tool I get:

```
$ couchdb2 -S https://host:6984/ -u admin -p secret --list
Traceback (most recent call last):
  File "/usr/local/bin/couchdb2", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/couchdb2.py", line 1291, in main
    execute(pargs, settings)
  File "/usr/local/lib/python3.7/site-packages/couchdb2.py", line 1138, in execute
    dbs = list(server)
  File "/usr/local/lib/python3.7/site-packages/couchdb2.py", line 81, in __iter__
    data = self._GET('_all_dbs').json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 888, in json
    return complexjson.loads(
AttributeError: module 'json' has no attribute 'loads'
```

I'm at a bit of a loss and judging by Google it doesn't appear too many people have run into this.

**Comment by pekrau** [comment]
Strange. It looks like it fails within the requests library. I have not tested CouchDB2 on Python 3.7. The closest I can find via Google is https://www.reddit.com/r/learnpython/comments/4m7q2y/attributeerror_module_object_has_no_attribute/ which is not helpful. I will look closer at this tomorrow when back at work.

**Comment by vdanen** [comment]
Thanks, any guidance here would be helpful as I don't have a copy of python 3.6 handy to test it with.

**Comment by pekrau** [comment]
@vdanen I am thoroughly mystified by this error. I am beginning to suspect that the error message is misleading, somehow. The error might not be in `requests` at all.

Have you written your own module called `json` (i.e. do you have a file `json.py` somewhere? Because such a module might overrun the standard Python module `json` and that would cause this kind of problem. If so, change the name of the file to `my_json.py` (or something) and try again.

**Comment by vdanen** [comment]
Hmmm... this is interesting.

```
Python 3.7.6 (default, Dec 30 2019, 19:38:26)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> print(json.__file__)
None
```

This is bizarre.  `/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py` exists but doesn't appear to be loaded.  I removed and reinstalled Brew's python3 and same results.  On my other mac this is fine so... something is definitely sideways here.  Apologies for wasting your time!  My script does work on the other mac so this isn't a problem with the couchdb2 module.
